/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnternehmenRouteImport } from './routes/unternehmen'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferenzenRouteImport } from './routes/referenzen'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as Karriere2RouteImport } from './routes/karriere 2'
import { Route as KarriereRouteImport } from './routes/karriere'
import { Route as Index2RouteImport } from './routes/index 2'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenzenIndexRouteImport } from './routes/referenzen.index'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen.index'
import { Route as ReferenzenNeubauRouteImport } from './routes/referenzen.neubau'
import { Route as ReferenzenGewerbeKommuneRouteImport } from './routes/referenzen.gewerbe-kommune'
import { Route as ReferenzenBauenImBestandRouteImport } from './routes/referenzen.bauen-im-bestand'
import { Route as LeistungenUmbauSanierungRouteImport } from './routes/leistungen.umbau-sanierung'
import { Route as LeistungenSchluesselfertigesBauenRouteImport } from './routes/leistungen.schluesselfertiges-bauen'
import { Route as LeistungenRohbauRouteImport } from './routes/leistungen.rohbau'

const UnternehmenRoute = UnternehmenRouteImport.update({
  id: '/unternehmen',
  path: '/unternehmen',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenRoute = ReferenzenRouteImport.update({
  id: '/referenzen',
  path: '/referenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const Karriere2Route = Karriere2RouteImport.update({
  id: '/karriere 2',
  path: '/karriere 2',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereRoute = KarriereRouteImport.update({
  id: '/karriere',
  path: '/karriere',
  getParentRoute: () => rootRouteImport,
} as any)
const Index2Route = Index2RouteImport.update({
  id: '/index 2',
  path: '/index 2',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenIndexRoute = ReferenzenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReferenzenRoute,
} as any)
const LeistungenIndexRoute = LeistungenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeistungenRoute,
} as any)
const ReferenzenNeubauRoute = ReferenzenNeubauRouteImport.update({
  id: '/neubau',
  path: '/neubau',
  getParentRoute: () => ReferenzenRoute,
} as any)
const ReferenzenGewerbeKommuneRoute =
  ReferenzenGewerbeKommuneRouteImport.update({
    id: '/gewerbe-kommune',
    path: '/gewerbe-kommune',
    getParentRoute: () => ReferenzenRoute,
  } as any)
const ReferenzenBauenImBestandRoute =
  ReferenzenBauenImBestandRouteImport.update({
    id: '/bauen-im-bestand',
    path: '/bauen-im-bestand',
    getParentRoute: () => ReferenzenRoute,
  } as any)
const LeistungenUmbauSanierungRoute =
  LeistungenUmbauSanierungRouteImport.update({
    id: '/umbau-sanierung',
    path: '/umbau-sanierung',
    getParentRoute: () => LeistungenRoute,
  } as any)
const LeistungenSchluesselfertigesBauenRoute =
  LeistungenSchluesselfertigesBauenRouteImport.update({
    id: '/schluesselfertiges-bauen',
    path: '/schluesselfertiges-bauen',
    getParentRoute: () => LeistungenRoute,
  } as any)
const LeistungenRohbauRoute = LeistungenRohbauRouteImport.update({
  id: '/rohbau',
  path: '/rohbau',
  getParentRoute: () => LeistungenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/index 2': typeof Index2Route
  '/karriere': typeof KarriereRoute
  '/karriere 2': typeof Karriere2Route
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/referenzen': typeof ReferenzenRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unternehmen': typeof UnternehmenRoute
  '/leistungen/rohbau': typeof LeistungenRohbauRoute
  '/leistungen/schluesselfertiges-bauen': typeof LeistungenSchluesselfertigesBauenRoute
  '/leistungen/umbau-sanierung': typeof LeistungenUmbauSanierungRoute
  '/referenzen/bauen-im-bestand': typeof ReferenzenBauenImBestandRoute
  '/referenzen/gewerbe-kommune': typeof ReferenzenGewerbeKommuneRoute
  '/referenzen/neubau': typeof ReferenzenNeubauRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/referenzen/': typeof ReferenzenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/index 2': typeof Index2Route
  '/karriere': typeof KarriereRoute
  '/karriere 2': typeof Karriere2Route
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unternehmen': typeof UnternehmenRoute
  '/leistungen/rohbau': typeof LeistungenRohbauRoute
  '/leistungen/schluesselfertiges-bauen': typeof LeistungenSchluesselfertigesBauenRoute
  '/leistungen/umbau-sanierung': typeof LeistungenUmbauSanierungRoute
  '/referenzen/bauen-im-bestand': typeof ReferenzenBauenImBestandRoute
  '/referenzen/gewerbe-kommune': typeof ReferenzenGewerbeKommuneRoute
  '/referenzen/neubau': typeof ReferenzenNeubauRoute
  '/leistungen': typeof LeistungenIndexRoute
  '/referenzen': typeof ReferenzenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/index 2': typeof Index2Route
  '/karriere': typeof KarriereRoute
  '/karriere 2': typeof Karriere2Route
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/referenzen': typeof ReferenzenRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unternehmen': typeof UnternehmenRoute
  '/leistungen/rohbau': typeof LeistungenRohbauRoute
  '/leistungen/schluesselfertiges-bauen': typeof LeistungenSchluesselfertigesBauenRoute
  '/leistungen/umbau-sanierung': typeof LeistungenUmbauSanierungRoute
  '/referenzen/bauen-im-bestand': typeof ReferenzenBauenImBestandRoute
  '/referenzen/gewerbe-kommune': typeof ReferenzenGewerbeKommuneRoute
  '/referenzen/neubau': typeof ReferenzenNeubauRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/referenzen/': typeof ReferenzenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/index 2'
    | '/karriere'
    | '/karriere 2'
    | '/kontakt'
    | '/leistungen'
    | '/referenzen'
    | '/sitemap.xml'
    | '/unternehmen'
    | '/leistungen/rohbau'
    | '/leistungen/schluesselfertiges-bauen'
    | '/leistungen/umbau-sanierung'
    | '/referenzen/bauen-im-bestand'
    | '/referenzen/gewerbe-kommune'
    | '/referenzen/neubau'
    | '/leistungen/'
    | '/referenzen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/index 2'
    | '/karriere'
    | '/karriere 2'
    | '/kontakt'
    | '/sitemap.xml'
    | '/unternehmen'
    | '/leistungen/rohbau'
    | '/leistungen/schluesselfertiges-bauen'
    | '/leistungen/umbau-sanierung'
    | '/referenzen/bauen-im-bestand'
    | '/referenzen/gewerbe-kommune'
    | '/referenzen/neubau'
    | '/leistungen'
    | '/referenzen'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/index 2'
    | '/karriere'
    | '/karriere 2'
    | '/kontakt'
    | '/leistungen'
    | '/referenzen'
    | '/sitemap.xml'
    | '/unternehmen'
    | '/leistungen/rohbau'
    | '/leistungen/schluesselfertiges-bauen'
    | '/leistungen/umbau-sanierung'
    | '/referenzen/bauen-im-bestand'
    | '/referenzen/gewerbe-kommune'
    | '/referenzen/neubau'
    | '/leistungen/'
    | '/referenzen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  Index2Route: typeof Index2Route
  KarriereRoute: typeof KarriereRoute
  Karriere2Route: typeof Karriere2Route
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRouteWithChildren
  ReferenzenRoute: typeof ReferenzenRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnternehmenRoute: typeof UnternehmenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unternehmen': {
      id: '/unternehmen'
      path: '/unternehmen'
      fullPath: '/unternehmen'
      preLoaderRoute: typeof UnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen': {
      id: '/referenzen'
      path: '/referenzen'
      fullPath: '/referenzen'
      preLoaderRoute: typeof ReferenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere 2': {
      id: '/karriere 2'
      path: '/karriere 2'
      fullPath: '/karriere 2'
      preLoaderRoute: typeof Karriere2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere': {
      id: '/karriere'
      path: '/karriere'
      fullPath: '/karriere'
      preLoaderRoute: typeof KarriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index 2': {
      id: '/index 2'
      path: '/index 2'
      fullPath: '/index 2'
      preLoaderRoute: typeof Index2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen/': {
      id: '/referenzen/'
      path: '/'
      fullPath: '/referenzen/'
      preLoaderRoute: typeof ReferenzenIndexRouteImport
      parentRoute: typeof ReferenzenRoute
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/referenzen/neubau': {
      id: '/referenzen/neubau'
      path: '/neubau'
      fullPath: '/referenzen/neubau'
      preLoaderRoute: typeof ReferenzenNeubauRouteImport
      parentRoute: typeof ReferenzenRoute
    }
    '/referenzen/gewerbe-kommune': {
      id: '/referenzen/gewerbe-kommune'
      path: '/gewerbe-kommune'
      fullPath: '/referenzen/gewerbe-kommune'
      preLoaderRoute: typeof ReferenzenGewerbeKommuneRouteImport
      parentRoute: typeof ReferenzenRoute
    }
    '/referenzen/bauen-im-bestand': {
      id: '/referenzen/bauen-im-bestand'
      path: '/bauen-im-bestand'
      fullPath: '/referenzen/bauen-im-bestand'
      preLoaderRoute: typeof ReferenzenBauenImBestandRouteImport
      parentRoute: typeof ReferenzenRoute
    }
    '/leistungen/umbau-sanierung': {
      id: '/leistungen/umbau-sanierung'
      path: '/umbau-sanierung'
      fullPath: '/leistungen/umbau-sanierung'
      preLoaderRoute: typeof LeistungenUmbauSanierungRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/leistungen/schluesselfertiges-bauen': {
      id: '/leistungen/schluesselfertiges-bauen'
      path: '/schluesselfertiges-bauen'
      fullPath: '/leistungen/schluesselfertiges-bauen'
      preLoaderRoute: typeof LeistungenSchluesselfertigesBauenRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/leistungen/rohbau': {
      id: '/leistungen/rohbau'
      path: '/rohbau'
      fullPath: '/leistungen/rohbau'
      preLoaderRoute: typeof LeistungenRohbauRouteImport
      parentRoute: typeof LeistungenRoute
    }
  }
}

interface LeistungenRouteChildren {
  LeistungenRohbauRoute: typeof LeistungenRohbauRoute
  LeistungenSchluesselfertigesBauenRoute: typeof LeistungenSchluesselfertigesBauenRoute
  LeistungenUmbauSanierungRoute: typeof LeistungenUmbauSanierungRoute
  LeistungenIndexRoute: typeof LeistungenIndexRoute
}

const LeistungenRouteChildren: LeistungenRouteChildren = {
  LeistungenRohbauRoute: LeistungenRohbauRoute,
  LeistungenSchluesselfertigesBauenRoute:
    LeistungenSchluesselfertigesBauenRoute,
  LeistungenUmbauSanierungRoute: LeistungenUmbauSanierungRoute,
  LeistungenIndexRoute: LeistungenIndexRoute,
}

const LeistungenRouteWithChildren = LeistungenRoute._addFileChildren(
  LeistungenRouteChildren,
)

interface ReferenzenRouteChildren {
  ReferenzenBauenImBestandRoute: typeof ReferenzenBauenImBestandRoute
  ReferenzenGewerbeKommuneRoute: typeof ReferenzenGewerbeKommuneRoute
  ReferenzenNeubauRoute: typeof ReferenzenNeubauRoute
  ReferenzenIndexRoute: typeof ReferenzenIndexRoute
}

const ReferenzenRouteChildren: ReferenzenRouteChildren = {
  ReferenzenBauenImBestandRoute: ReferenzenBauenImBestandRoute,
  ReferenzenGewerbeKommuneRoute: ReferenzenGewerbeKommuneRoute,
  ReferenzenNeubauRoute: ReferenzenNeubauRoute,
  ReferenzenIndexRoute: ReferenzenIndexRoute,
}

const ReferenzenRouteWithChildren = ReferenzenRoute._addFileChildren(
  ReferenzenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  Index2Route: Index2Route,
  KarriereRoute: KarriereRoute,
  Karriere2Route: Karriere2Route,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRouteWithChildren,
  ReferenzenRoute: ReferenzenRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnternehmenRoute: UnternehmenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
